
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 22 07:36:39 CST 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ITS_INT = 36;
  public static final int ITS_FOR = 25;
  public static final int ITS_ENDCASE = 32;
  public static final int ITS_AND = 21;
  public static final int ITS_OR = 22;
  public static final int ITS_RETURN = 27;
  public static final int ITS_IF = 13;
  public static final int ITS_MAIN = 9;
  public static final int ITS_ID = 40;
  public static final int ITS_COMMA = 7;
  public static final int ITS_TRUE = 35;
  public static final int ITS_SWITCH = 30;
  public static final int ITS_OPREL = 24;
  public static final int ITS_DIGIT = 12;
  public static final int ITS_PAR_R = 17;
  public static final int ITS_QUOTE = 20;
  public static final int ITS_VOID = 26;
  public static final int ITS_LETTER = 33;
  public static final int ITS_PAR_L = 16;
  public static final int ITS_DIGITFLOAT = 14;
  public static final int ITS_ELSE = 28;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int ITS_BOOLEAN = 38;
  public static final int ITS_COLON = 29;
  public static final int ITS_OPMULT = 3;
  public static final int ITS_WHILE = 15;
  public static final int ITS_SEMICOLON = 11;
  public static final int ITS_FLOAT = 23;
  public static final int ITS_FUNCTION = 6;
  public static final int ITS_COMPARE = 8;
  public static final int ITS_EQUALS = 4;
  public static final int ITS_FALSE = 34;
  public static final int ITS_OPINCDEC = 5;
  public static final int ITS_CURLY_I = 18;
  public static final int ITS_CHAR = 37;
  public static final int ITS_ASSIGNAMENT = 39;
  public static final int ITS_PRINT = 10;
  public static final int ITS_CURLY_D = 19;
  public static final int ITS_CASE = 31;
  public static final int ITS_OPSUM = 2;
}

