/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package min_c;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_cup.Lexer;
import java_cup.runtime.Symbol;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author jamvi
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtCodigo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        btSubir = new javax.swing.JButton();
        btAnalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtCodigo.setColumns(20);
        txtCodigo.setRows(5);
        jScrollPane1.setViewportView(txtCodigo);

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane2.setViewportView(txtResultado);

        btSubir.setText("Cargar");
        btSubir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSubirMouseClicked(evt);
            }
        });
        btSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubirActionPerformed(evt);
            }
        });

        btAnalizar.setText("Analizar");
        btAnalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAnalizarMouseClicked(evt);
            }
        });
        btAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btAnalizar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSubir)
                    .addComponent(btAnalizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnalizarActionPerformed
        // TODO add your handling code here:

        txtResultado.setText("");
        //txtCodigo
        LexicalElements lexer;
        parser pars = null;
        try {
            lexer = new LexicalElements(new FileReader(archivo));
            pars = new parser(lexer);
            pars.parse();

            for (int i = 0; i < pars.output.size(); i++) {
                txtResultado.append(pars.output.get(i).toString() + "\n");
            }

        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        //start
        
        /*try {
            parser p = new parser(new LexicalElements(new FileReader(archivo)));
            p.parse();

            // TODO: Validar que solo cree el árbol cuando no hayan errores.
            if ((LexicalElements.erroresLexicos == 0) && (parser.erroresSintacticos == 0)) {
                Nodo root = parser.padre;
                Graficar(recorrido(root));
                System.out.println("El AST fue generado correctamente.");
            } else {
                System.out.println("No se generó el AST.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        */
        
        


    }//GEN-LAST:event_btAnalizarActionPerformed

    private void btSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubirActionPerformed
        // TODO add your handling code here:
        //filechooser
        //file archivo =new file(ruta)

    }//GEN-LAST:event_btSubirActionPerformed

    private void btSubirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSubirMouseClicked
        // TODO add your handling code here:
        
        JFileChooser chooser = new JFileChooser("C:\\Users\\guill\\Desktop\\Rubber Ducky");
        chooser.showOpenDialog(null);
        String ruta = chooser.getSelectedFile().getAbsolutePath();
        archivo = new File(ruta);

        //adding
        String texto = "", aux = "";
        if (archivo != null) {
            FileReader archivos = null;
            try {
                archivos = new FileReader(archivo);
            } catch (FileNotFoundException ex) {
            }
            BufferedReader lee = new BufferedReader(archivos);
            try {
                while ((aux = lee.readLine()) != null) {
                    texto += aux + "\n";
                }
                txtCodigo.setText(texto);
                codigoabierto = true;
            } catch (IOException ex) {
                System.out.println("no eligio ningun archivo");
            }
            try {
                lee.close();
            } catch (IOException ex) {
                System.out.println("no eligio ningun archivo");
            }
        } else {
            JOptionPane.showMessageDialog(null, "" + "\nNo se ha encontrado el archivo", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

  

    }//GEN-LAST:event_btSubirMouseClicked

    private void btAnalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAnalizarMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_btAnalizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnalizar;
    private javax.swing.JButton btSubir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtCodigo;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
File archivo = new File("C:\\Users\\guill\\Desktop\\Rubber Ducky\\pruebaSimple.txt");
    boolean codigoabierto = false;
    
    
    
    
    public static String recorrido(Nodo raiz) {
  		String cuerpo = "";
    	for (Nodo child : raiz.hijos) {
    		// System.out.println("hola");
      		if (!(child.getEtiqueta().equals("vacio"))) {
        		cuerpo += "\"" + raiz.getID() + ". " + raiz.getEtiqueta() + " = " + raiz.getValor() +
        			"\"->\""+ child.getID() +". " + child.getEtiqueta()  + " = " + child.getValor() + "\""  + "\n";
        		cuerpo += recorrido(child);
      		}
    	}
    	return cuerpo;
	}
    
    public static void Graficar(String cadena) {
		FileWriter fw = null;
    	PrintWriter pw = null;
    	String archivo2 = "AST.dot";
    	try {
        	fw = new FileWriter(archivo2);
        	pw = new PrintWriter(fw);
        	pw.println("digraph G {");
        	pw.println(cadena);
        	pw.println("\n}");
        	fw.close();
    	} catch (Exception e) {
        	System.out.println(e);
    	}
    	try {
        	String cmd = "dot -Tpng AST.dot -o fotoAST.png"; 
        	Runtime.getRuntime().exec(cmd);
    	} catch (IOException ioe) {
        	System.out.println(ioe);
    	}
	}
}
