
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Sep 18 23:29:45 CST 2022
//----------------------------------------------------

package min_c;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ITSFOR = 12;
  public static final int ITSBRA_L = 24;
  public static final int ITSDOUBLE = 33;
  public static final int ITSAND = 30;
  public static final int ITSDECLARE = 3;
  public static final int ITSCOMMA = 39;
  public static final int ITSOPREL = 21;
  public static final int ITSPAR_R = 27;
  public static final int ITSEXIT = 28;
  public static final int ITSOR = 31;
  public static final int ITSPAR_L = 26;
  public static final int ITSMAIN = 2;
  public static final int ITSIF = 15;
  public static final int ITSTRUE = 10;
  public static final int ITSID = 4;
  public static final int ITSRETURN = 18;
  public static final int ITSNULL = 19;
  public static final int ITSVOID = 36;
  public static final int ITSCOLON = 14;
  public static final int EOF = 0;
  public static final int ITSCHARACTER = 38;
  public static final int ITSNUMDOUBLE = 7;
  public static final int ITSELSE = 16;
  public static final int ITSWHILE = 13;
  public static final int error = 1;
  public static final int ITSSEMICOLON = 20;
  public static final int ITSCOMMENT = 29;
  public static final int ITSBRK = 17;
  public static final int ITSTHEN = 35;
  public static final int ITSFALSE = 11;
  public static final int ITSNUMINT = 6;
  public static final int ITSFUNCTION = 40;
  public static final int ITSBRACKET_R = 44;
  public static final int ITSSTRING = 8;
  public static final int ITSASSIGNMENT = 5;
  public static final int ITSBRACKET_L = 43;
  public static final int ITSOPSUM = 23;
  public static final int ITSOPMULT = 22;
  public static final int ITSCONST = 41;
  public static final int ITSSTR = 34;
  public static final int ITSCHAR = 9;
  public static final int ITSBOOLEAN = 37;
  public static final int ITSINT = 32;
  public static final int ITSBRA_R = 25;
  public static final int ITSARRAY = 42;
}

