
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 29 17:37:15 CST 2022
//----------------------------------------------------

package min_c;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ITSFOR = 11;
  public static final int ITSBRA_L = 25;
  public static final int ITSAND = 32;
  public static final int ITSDECLARE = 3;
  public static final int ITSCOMMA = 40;
  public static final int ITSSCENARIO = 14;
  public static final int ITSDFT = 29;
  public static final int ITSOPREL = 22;
  public static final int ITSPAR_R = 28;
  public static final int ITSEXIT = 30;
  public static final int ITSOR = 33;
  public static final int ITSPAR_L = 27;
  public static final int ITSMAIN = 2;
  public static final int ITSIF = 16;
  public static final int ITSTRUE = 9;
  public static final int ITSID = 4;
  public static final int ITSRETURN = 19;
  public static final int ITSNULL = 20;
  public static final int ITSVOID = 37;
  public static final int ITSCOLON = 13;
  public static final int EOF = 0;
  public static final int ITSCHARACTER = 39;
  public static final int ITSELSE = 17;
  public static final int ITSWHILE = 12;
  public static final int error = 1;
  public static final int ITSSWITCH = 15;
  public static final int ITSSEMICOLON = 21;
  public static final int ITSCOMMENT = 31;
  public static final int ITSBRK = 18;
  public static final int ITSTHEN = 36;
  public static final int ITSFALSE = 10;
  public static final int ITSNUMINT = 6;
  public static final int ITSFUNCTION = 41;
  public static final int ITSBRACKET_R = 45;
  public static final int ITSSTRING = 7;
  public static final int ITSASSIGNMENT = 5;
  public static final int ITSBRACKET_L = 44;
  public static final int ITSOPSUM = 24;
  public static final int ITSOPMULT = 23;
  public static final int ITSCONST = 42;
  public static final int ITSSTR = 35;
  public static final int ITSCHAR = 8;
  public static final int ITSBOOLEAN = 38;
  public static final int ITSINT = 34;
  public static final int ITSBRA_R = 26;
  public static final int ITSARRAY = 43;
}

